### ISSUE TITLE
Unable to fetch movie details

### ISSUE THREAD

**Issue by TubbyStubby** [Fowres-Co/personal-movie-dashboard#2]
getting error `'NoneType' object is not iterable`
traceback:
```
Traceback (most recent call last):
  File "c:/Projects/Python/personal-movie-dashboard/app.py", line 29, in <module>
    details = scrapy.movieDetails(spidy.fileNamesC[base]['cleaned'], spidy.fileNamesC[base]['yr'],1) #using 1 for testing
  File "c:\Projects\Python\personal-movie-dashboard\IMDB_scraper.py", line 31, in movieDetails
    title,rel=self.search(s,year,ty)
```

**Comment by TubbyStubby** [comment]
Extra leading and ending whitespaces causing problems.
